kind: Service
apiVersion: v1
metadata:
  name: ngsa
  labels:
    app: ngsa
spec:
  selector:
    app: ngsa
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa
  labels:
    app: ngsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa
  template:
    metadata:
      labels:
        app: ngsa
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ngsa"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: app
        image: k3d-registry.localhost:5000/ngsa-dapr:local
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        args:
          - --in-memory
          - --dapr
          - --prometheus
          - --log-level
          - Warning
          - --request-log-level
          - Information
          - --zone
          - dev
          - --region
          - dev
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
